# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('CallID', models.IntegerField(primary_key=True, serialize=False)),
                ('ContactPersonName', models.CharField(blank=True, max_length=200)),
                ('ContactPersonNumber', models.IntegerField(blank=True)),
                ('Datetime', models.DateTimeField(verbose_name='date time received')),
                ('BriefDescription', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Crisis',
            fields=[
                ('CrisisID', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=200)),
                ('DateTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('PlanID', models.IntegerField(primary_key=True, serialize=False)),
                ('isApprovedByPMO', models.BooleanField(default=False)),
                ('isApprovedByGeneral', models.BooleanField(default=False)),
                ('Datetime', models.DateTimeField(verbose_name='date time of plan submission')),
                ('CrisisType', models.CharField(max_length=200)),
                ('AnalysisOfCase', models.CharField(max_length=255)),
                ('Map', models.URLField(verbose_name='map url')),
                ('CrisisID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMOBackend.Crisis')),
            ],
        ),
        migrations.CreateModel(
            name='SuggestedActions',
            fields=[
                ('ActionID', models.IntegerField(primary_key=True, serialize=False)),
                ('TypeTroop', models.CharField(choices=[('MIL', 'Military'), ('BDP', 'Bomb Disposal'), ('CGD', 'Coast Guard'), ('HAZ', 'Hazmat'), ('SNR', 'Search and Rescue'), ('CEV', 'Civilian Evacuation'), ('AMB', 'Ambulance'), ('ETC', 'Emergency Traffic Control'), ('FFT', 'Firefighters'), ('IDQ', 'Infectious Disease Quarantine Personnel')], max_length=3)),
                ('SeverityLevel', models.IntegerField()),
                ('PlanID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMOBackend.Plan')),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('UpdateID', models.IntegerField(primary_key=True, serialize=False)),
                ('DateTime', models.DateTimeField(verbose_name='Date Published')),
                ('Status', models.CharField(max_length=10)),
                ('Comment', models.CharField(max_length=255)),
                ('Location', models.CharField(max_length=200)),
                ('SeverityLevel', models.IntegerField()),
                ('CrisisID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMOBackend.Crisis')),
            ],
        ),
        migrations.AddField(
            model_name='call',
            name='CrisisID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMOBackend.Crisis'),
        ),
    ]
