# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 13:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMOBackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='BriefDescription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='AnalysisOfCase',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='CrisisType',
            field=models.CharField(choices=[('TR', 'Terrorist'), ('ND', 'Natural Disaster'), ('EP', 'Epidemic')], max_length=2),
        ),
        migrations.AlterField(
            model_name='suggestedactions',
            name='SeverityLevel',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='update',
            name='SeverityLevel',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
