# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMOBackend', '0003_auto_20171011_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='CallID',
        ),
        migrations.RemoveField(
            model_name='crisis',
            name='CrisisID',
        ),
        migrations.RemoveField(
            model_name='suggestedactions',
            name='ActionID',
        ),
        migrations.RemoveField(
            model_name='update',
            name='UpdateID',
        ),
        migrations.AddField(
            model_name='call',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crisis',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestedactions',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='update',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
