# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMOBackend', '0004_auto_20171011_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='crisis',
            name='Cleared',
            field=models.BooleanField(default=False),
        ),
    ]
