# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMOBackend', '0005_crisis_cleared'),
    ]

    operations = [
        migrations.AddField(
            model_name='crisis',
            name='CrisisID',
            field=models.IntegerField(default=0),
        ),
    ]
