# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMOBackend', '0007_auto_20171018_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.TextField()),
                ('PlanID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMOBackend.Plan')),
            ],
        ),
        migrations.AlterField(
            model_name='crisis',
            name='CrisisStatus',
            field=models.CharField(choices=[('NC', 'New Crisis, Awaiting Plan'), ('PF', 'Plan Formed, Awaiting Authorization'), ('PAG', 'Approved by General, Awaiting Authorization'), ('PAP', 'Authorized, Awaiting Activation'), ('PJP', 'Plan Rejected, Replanning Required'), ('PA', 'Plan In Action'), ('UP', 'New Update Received'), ('CO', 'Crisis Cleared')], default='NC', max_length=3),
        ),
    ]
