# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMOBackend', '0010_auto_20171022_0540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='DateTime',
        ),
        migrations.RemoveField(
            model_name='update',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='update',
            name='SeverityLevel',
        ),
        migrations.AddField(
            model_name='update',
            name='PlanID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CMOBackend.Plan'),
            preserve_default=False,
        ),
    ]
